### ISSUE TITLE
HF demo does not work and has an error

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/chatarena#81]
See https://huggingface.co/spaces/chatarena/chatarena-demo

**Comment by elliottower** [comment]
@yuxiang-wu @ZhengyaoJiang if either of you guys could give me access to the HuggingFace space or fix it yourself that would be great. Not sure how to fix this otherwise.

**Comment by elliottower** [comment]
Update to this I have tested it out locally quite some bit and have the UI at least working in the HF space -- I have hard coded the versions of pydantic and gradio to be the same as they were previously, but there still seems to be a bizarre error:

```Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/user/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by elliottower** [comment]
I believe that error above is due to the database? Not 100% sure, but will fix this in the next few days hopefully.

**Comment by elliottower** [comment]
Okay I seem to have fixed it, I'm going to close this
